# Generated by Django 4.1 on 2022-09-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=20, null=True)),
                ("date", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
