# Generated by Django 4.1 on 2022-09-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="label",
            new_name="title",
        ),
    ]
